/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYPDF
#define ROOMYPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TH1F.h"
#include "fastgl.h"
#include <vector>
#include "DebugTimeInfo.h"

class RooMyPdf : public RooAbsPdf
{
public:
    RooMyPdf()
    {};

    RooMyPdf(const char *name, const char *title,
             RooAbsReal &_x, RooAbsReal &_mean, RooAbsReal &_width, int _bins = 10000, int _method = 0,
             DebugTimeInfo *debug = nullptr);

    RooMyPdf(const RooMyPdf &other, const char *name = 0);

    virtual TObject *clone(const char *newname) const
    { return new RooMyPdf(*this, newname); }

    inline virtual ~RooMyPdf()
    {
        if (temp != nullptr) {
            delete temp;
        }
    }

    void cuda_gaus_prepare();

protected:

    RooRealProxy x;
    RooRealProxy width;
    RooRealProxy mean;
    int method;
    int bins;

    fastgl::QuadPair *temp = nullptr;
    std::vector<double> gaus_x;
    std::vector<double> gaus_w;

    Double_t gaus_evaluate() const;

    Double_t normal_evaluate() const;

    Double_t cuda_normal_evaluate() const;

    Double_t cuda_normal_evaluate_tuned() const;

    Double_t cuda_gaus_evaluate() const;

    Double_t evaluate() const;

private:

    Double_t sub_evaluate(Double_t x) const;

    Double_t sub_f(Double_t x) const;

    Double_t sub_sigma(Double_t x) const;

    DebugTimeInfo *debug;

ClassDef(RooMyPdf, 1) // Your description goes here...
};

#endif
